# Generated by Django 4.2.7 on 2025-12-11 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements_text', models.TextField()),
                ('parsed_requirements', models.JSONField(default=dict)),
                ('results', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('product_name', models.CharField(max_length=500)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('amazon_link', models.URLField(blank=True, null=True)),
                ('flipkart_link', models.URLField(blank=True, null=True)),
                ('product_image', models.URLField(blank=True, null=True)),
                ('match_score', models.FloatField(default=0)),
                ('match_reasons', models.JSONField(default=list)),
                ('rating', models.FloatField(default=0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='recommendations.requirementquery')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
