# Generated by Django 4.2.7 on 2026-01-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productresult',
            name='amazon_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productresult',
            name='brand',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productresult',
            name='flipkart_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productresult',
            name='product_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productresult',
            name='product_name',
            field=models.CharField(max_length=1000),
        ),
    ]
