# Generated by Django 4.2.7 on 2026-01-12 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0002_alter_productresult_amazon_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(help_text='Name of the metric (e.g., api_response_time)', max_length=100)),
                ('metric_value', models.FloatField(help_text='Numeric value of the metric')),
                ('metric_type', models.CharField(choices=[('counter', 'Counter'), ('gauge', 'Gauge'), ('histogram', 'Histogram'), ('timing', 'Timing')], default='gauge', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metric data')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags for filtering (e.g., ['api', 'predictions'])")),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Metric',
                'verbose_name_plural': 'System Metrics',
                'db_table': 'system_metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_name', '-timestamp'], name='system_metr_metric__bf467a_idx'), models.Index(fields=['metric_type'], name='system_metr_metric__054eaf_idx'), models.Index(fields=['-timestamp'], name='system_metr_timesta_f576a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Configuration key', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Configuration value (stored as string)')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(help_text='Description of this setting')),
                ('category', models.CharField(blank=True, help_text="Setting category (e.g., 'email', 'ml_model')", max_length=50)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Hide value in admin UI')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'db_table': 'system_configurations',
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['key'], name='system_conf_key_35f9ec_idx'), models.Index(fields=['category'], name='system_conf_categor_a4e81d_idx')],
            },
        ),
    ]
