# Generated by Django 4.2.7 on 2026-01-12 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned_from_messaging',
            field=models.BooleanField(default=False, help_text='Banned from sending messages'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Account suspended by admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_by',
            field=models.ForeignKey(blank=True, help_text='Admin who suspended this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Reason for suspension'),
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_suspend', 'User Suspended'), ('user_activate', 'User Activated'), ('user_delete', 'User Deleted'), ('user_verify', 'User Email Verified'), ('user_password_reset', 'User Password Reset'), ('listing_approve', 'Listing Approved'), ('listing_reject', 'Listing Rejected'), ('listing_flag', 'Listing Flagged as Fraud'), ('listing_delete', 'Listing Deleted'), ('listing_edit', 'Listing Edited'), ('message_delete', 'Message Deleted'), ('user_ban_messaging', 'User Banned from Messaging'), ('settings_update', 'System Settings Updated'), ('report_generate', 'Report Generated'), ('data_export', 'Data Exported'), ('other', 'Other Action')], max_length=50)),
                ('target_model', models.CharField(help_text='Model name (User, Listing, etc.)', max_length=50)),
                ('target_id', models.IntegerField(blank=True, help_text='ID of the affected object', null=True)),
                ('description', models.TextField(help_text='Detailed description of the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional action data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Action Log',
                'verbose_name_plural': 'Admin Action Logs',
                'db_table': 'admin_action_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', '-created_at'], name='admin_actio_admin_u_a16902_idx'), models.Index(fields=['action_type', '-created_at'], name='admin_actio_action__4e777c_idx'), models.Index(fields=['target_model', 'target_id'], name='admin_actio_target__67505c_idx'), models.Index(fields=['-created_at'], name='admin_actio_created_eabff4_idx')],
            },
        ),
    ]
